project_id = "eeaqaryoyxbuqyxqczab"

[functions.generate-scenario]
verify_jwt = false

[functions.generate-sales-response]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.public-api]
verify_jwt = false
